# Generated by Django 5.0.7 on 2024-07-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
